# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class CliToolbox < Formula
  desc "A collection of various cli tools"
  homepage "https://github.com/tiborhercz/cli-toolbox"
  version "0.1.5"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/tiborhercz/cli-toolbox/releases/download/v0.1.5/cli-toolbox_0.1.5_darwin_amd64.tar.gz"
      sha256 "2e4c92801f79bd27221d2b20443dc975fd8d5d33b64679806a9b374a5c83c60a"

      def install
        bin.install "cli-toolbox"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/tiborhercz/cli-toolbox/releases/download/v0.1.5/cli-toolbox_0.1.5_linux_amd64.tar.gz"
      sha256 "66ba6bab7e678d92158853effd98209e584186db030c3203555ebfbfb9933424"

      def install
        bin.install "cli-toolbox"
      end
    end
  end

  test do
    system "#{bin}/cli-toolbox -v"
  end
end
