# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class CliToolbox < Formula
  desc "A collection of various cli tools"
  homepage "https://github.com/tiborhercz/cli-toolbox"
  version "0.1.4"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/tiborhercz/cli-toolbox/releases/download/v0.1.4/cli-toolbox_0.1.4_darwin_amd64.tar.gz"
      sha256 "b6031cab8dccb610f92b76502e43c62443fa351fe488d1fffac0c4f3e5ae59c7"

      def install
        bin.install "cli-toolbox"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/tiborhercz/cli-toolbox/releases/download/v0.1.4/cli-toolbox_0.1.4_linux_amd64.tar.gz"
      sha256 "7d40006ea775e8f513ebc125fa2908ef5bdefe5081534fbaadd932f3e09c2e69"

      def install
        bin.install "cli-toolbox"
      end
    end
  end

  test do
    system "#{bin}/cli-toolbox -v"
  end
end
