# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class CliToolbox < Formula
  desc "A collection of various cli tools"
  homepage "https://github.com/tiborhercz/cli-toolbox"
  version "0.2.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/tiborhercz/cli-toolbox/releases/download/v0.2.0/cli-toolbox_0.2.0_darwin_amd64.tar.gz"
      sha256 "c8b37300104091c1c6a132c419af1f8b7030566a0c1e45a375108b8c64521308"

      def install
        bin.install "cli-toolbox"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/tiborhercz/cli-toolbox/releases/download/v0.2.0/cli-toolbox_0.2.0_linux_amd64.tar.gz"
      sha256 "9168b4794f912c7eb491717d1a5c4100e577504123c9c9de7cf73c530149e1af"

      def install
        bin.install "cli-toolbox"
      end
    end
  end

  test do
    system "#{bin}/cli-toolbox -v"
  end
end
