# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Toolbox < Formula
  desc "A collection of various cli tools"
  homepage "https://github.com/tiborhercz/toolbox"
  version "0.7.1"
  license "MIT"

  on_macos do
    url "https://github.com/tiborhercz/toolbox/releases/download/v0.7.1/toolbox_0.7.1_darwin_amd64.tar.gz"
    sha256 "dc16920f4407c87de91e12ec3697dd7fcecc3deba51eaa53054c9c9eb68992a3"

    def install
      bin.install "toolbox"
    end

    if Hardware::CPU.arm?
      def caveats
        <<~EOS
          The darwin_arm64 architecture is not supported for the Toolbox
          formula at this time. The darwin_amd64 binary may work in compatibility
          mode, but it might not be fully supported.
        EOS
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/tiborhercz/toolbox/releases/download/v0.7.1/toolbox_0.7.1_linux_amd64.tar.gz"
      sha256 "63892fb7ae710411fc0ef66b12c89d0d2efcdef2b68cb62ee475e862cebafc7a"

      def install
        bin.install "toolbox"
      end
    end
  end

  test do
    system "#{bin}/toolbox -v"
  end
end
