# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Toolbox < Formula
  desc "A collection of various cli tools"
  homepage "https://github.com/tiborhercz/toolbox"
  version "0.6.1"
  license "MIT"

  on_macos do
    url "https://github.com/tiborhercz/toolbox/releases/download/v0.6.1/toolbox_0.6.1_darwin_amd64.tar.gz"
    sha256 "b2ce653eeab7af6d5284b3f3b198e0b631e1d304c6812dbd524d7586abcd9443"

    def install
      bin.install "toolbox"
    end

    if Hardware::CPU.arm?
      def caveats
        <<~EOS
          The darwin_arm64 architecture is not supported for the Toolbox
          formula at this time. The darwin_amd64 binary may work in compatibility
          mode, but it might not be fully supported.
        EOS
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/tiborhercz/toolbox/releases/download/v0.6.1/toolbox_0.6.1_linux_amd64.tar.gz"
      sha256 "664e8ce2905aac010f1b88517b89b8782d8ba58616d68c326e420bbae2d8f389"

      def install
        bin.install "toolbox"
      end
    end
  end

  test do
    system "#{bin}/toolbox -v"
  end
end
