# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Toolbox < Formula
  desc "A collection of various cli tools"
  homepage "https://github.com/tiborhercz/toolbox"
  version "0.6.0"
  license "MIT"

  on_macos do
    url "https://github.com/tiborhercz/toolbox/releases/download/v0.6.0/toolbox_0.6.0_darwin_amd64.tar.gz"
    sha256 "51d5536b6be9fddbd153587fc5da62ab5414d0d61346b5b8517fafd372ee1027"

    def install
      bin.install "toolbox"
    end

    if Hardware::CPU.arm?
      def caveats
        <<~EOS
          The darwin_arm64 architecture is not supported for the Toolbox
          formula at this time. The darwin_amd64 binary may work in compatibility
          mode, but it might not be fully supported.
        EOS
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/tiborhercz/toolbox/releases/download/v0.6.0/toolbox_0.6.0_linux_amd64.tar.gz"
      sha256 "19187ba86bd2cd7d47b41f0a51b64c456fb6d48498ae7a81a62df2b168f40fb3"

      def install
        bin.install "toolbox"
      end
    end
  end

  test do
    system "#{bin}/toolbox -v"
  end
end
